#extending everything from tomcat image ...
FROM tomcat
MAINTAINER jp
# COPY path-to-your-application-war path-to-webapps-in-docker-tomcat
COPY target/simulatorMiddleware-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
